### ISSUE TITLE
updates/changes?

### ISSUE THREAD

**Issue by jamesdixon** [chgeuer/postgres-azure#2]
Hi @chgeuer - stumbled upon this guide and was curious if there was anything you'd change now that it's almost a year later? For example, I know now that premium storage is available in the DS series. Would that negate the need for RAID? Thanks!

**Comment by chgeuer** [comment]
Hi @jamesdixon,

whether you use RAID/Striped disks, and/or premium storage, is up to you and the requirements of your app. You're right that premium storage is faster than standard storage, but even for premium storage people use striping, either for even more performance, or larger volumes. 

I think the biggest unsolved problem is orchestration of the overall cluster, i.e. determining whether a failover and re-election of a new master needs to happen. Corosync/Pacemaker or Apache ZooKeeper come to mind. (https://github.com/jinty/zgres or https://github.com/zalando/patroni look interesting here). 

Besides that, of course Azure Resource Manager is the way to bring up the infrastructure as well. It's on my TODO list, but very low right now.
